CNN_encoder: Voxel3DCNN
CNN_first_layer_channels: 256
CNN_layers: 4
GNN_conv: GATv2
GNN_dropout: 0.3
GNN_encoder: GNNEncoder2
GNN_layers: 3
GNN_output_dim: 4096
MLP_hidden_dim: 4096
MLP_hidden_layers: 2
MLP_projector: true
batch_size: 64
context: before
data_set: PDBbind_2020
data_split: core
dropout: 0.3
exclude_hydrogens: false
learning_rate: 0.001
max_epochs: 600
node_pooling: add
pos_embedding_dim: 240
types_embedding_dim: 1024
use_exclusion_channels: true
weight_decay: 1.0e-06
accumulate_grad_batches: 4
